name: Publish to npm

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Update package.json version from tag
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "Setting version to $TAG"
          if grep -q '"version":' package.json; then
            sed -i -E "s/\"version\": *\"[^\"]*\"/\"version\": \"${TAG}\"/" package.json
          else
            sed -i "1s/^/{\n  \"version\": \"${TAG}\",\n/" package.json
          fi

      - name: Build project
        run: npm run build

      - name: Publish package to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
